const ClientsData = [
  { id: 1, image_url: "/images/clients/acc.jpg" },
  { id: 2, image_url: "/images/clients/blue-dart.jpg" },
  { id: 3, image_url: "/images/clients/bullows.jpg" },
  { id: 4, image_url: "/images/clients/cushman-weikfield.jpg" },
  { id: 5, image_url: "/images/clients/datwyler.jpg" },
  { id: 6, image_url: "/images/clients/givaudan.jpg" },
  { id: 7, image_url: "/images/clients/hatsun-agro.jpg" },
  { id: 8, image_url: "/images/clients/Hero.jpg" },
  { id: 9, image_url: "/images/clients/hsil.jpg" },
  { id: 10, image_url: "/images/clients/india-japan-lighting.jpg" },
  { id: 11, image_url: "/images/clients/indospace.jpg" },
  { id: 12, image_url: "/images/clients/johnson-matthey.jpg" },
  { id: 13, image_url: "/images/clients/lm-wind.jpg" },
  { id: 14, image_url: "/images/clients/lt-logo.jpg" },
  { id: 15, image_url: "/images/clients/lumax.jpg" },
  { id: 16, image_url: "/images/clients/posco.jpg" },
  { id: 17, image_url: "/images/clients/reckit-benckiser.jpg" },
  { id: 18, image_url: "/images/clients/reitzel-india.jpg" },
  { id: 19, image_url: "/images/clients/rmz-corp-logo.jpg" },
  { id: 20, image_url: "/images/clients/shapoorji-pallonji.jpg" },
  { id: 21, image_url: "/images/clients/sterling-wilson.jpg" },
  { id: 22, image_url: "/images/clients/taiksha.jpg" },
  { id: 23, image_url: "/images/clients/torrent-pharma.jpg" },
  { id: 24, image_url: "/images/clients/torrent-pharma.jpg" },
];

export default ClientsData;
